name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew clean build
      env:
        GITHUB_USER: "github"
        GITHUB_TOKEN: ${{ github.token }}
      